# Generated by Django 5.0.8 on 2024-09-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_address_status_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
